# Generated by Django 6.0.5 on 2026-06-08 19:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('variation_manager_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
