# Generated by Django 6.0.5 on 2026-06-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassItem',
            new_name='CartItem',
        ),
    ]
